""""NewFeatures"

Revision ID: 07d54dd5add9
Revises: 8d82cb696e3b
Create Date: 2025-06-27 17:23:40.672570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d54dd5add9'
down_revision: Union[str, None] = '8d82cb696e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('student_cumulative_results',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('cumulative_gpa', sa.Float(), nullable=True),
    sa.Column('cumulative_score', sa.Float(), nullable=True),
    sa.Column('overall_cumulative_grade', sa.String(length=10), nullable=True),
    sa.Column('overall_cumulative_position', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_session_id', name='_student_academic_session_uc')
    )
    op.create_index(op.f('ix_student_cumulative_results_id'), 'student_cumulative_results', ['id'], unique=False)
    op.create_index(op.f('ix_student_cumulative_results_school_id'), 'student_cumulative_results', ['school_id'], unique=False)
    op.create_table('subject_results',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', name='_student_subject_term_uc')
    )
    op.create_index(op.f('ix_subject_results_id'), 'subject_results', ['id'], unique=False)
    op.create_index(op.f('ix_subject_results_school_id'), 'subject_results', ['school_id'], unique=False)
    op.create_table('term_results',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('total_gpa', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('overall_grade', sa.String(length=10), nullable=True),
    sa.Column('position_in_class', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', name='_student_term_uc')
    )
    op.create_index(op.f('ix_term_results_id'), 'term_results', ['id'], unique=False)
    op.create_index(op.f('ix_term_results_school_id'), 'term_results', ['school_id'], unique=False)
    op.add_column('academic_sessions', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('academic_sessions', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('terms', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('terms', sa.Column('locked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'locked_at')
    op.drop_column('terms', 'is_locked')
    op.drop_column('academic_sessions', 'locked_at')
    op.drop_column('academic_sessions', 'is_locked')
    op.drop_index(op.f('ix_term_results_school_id'), table_name='term_results')
    op.drop_index(op.f('ix_term_results_id'), table_name='term_results')
    op.drop_table('term_results')
    op.drop_index(op.f('ix_subject_results_school_id'), table_name='subject_results')
    op.drop_index(op.f('ix_subject_results_id'), table_name='subject_results')
    op.drop_table('subject_results')
    op.drop_index(op.f('ix_student_cumulative_results_school_id'), table_name='student_cumulative_results')
    op.drop_index(op.f('ix_student_cumulative_results_id'), table_name='student_cumulative_results')
    op.drop_table('student_cumulative_results')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    # ### end Alembic commands ###
