"""empty message

Revision ID: 5e1193696cbf
Revises: bbd521313431
Create Date: 2025-06-28 13:21:08.987025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1193696cbf'
down_revision: Union[str, None] = 'bbd521313431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('platform_fee_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('school_net_amount', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('paystack_subaccount_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'paystack_subaccount_id')
    op.drop_column('payments', 'school_net_amount')
    op.drop_column('payments', 'platform_fee_amount')
    # ### end Alembic commands ###
