""""Implement_dynamic_admission_forms"

Revision ID: 619764b79113
Revises: 69fda1fb161b
Create Date: 2025-06-28 11:18:27.274476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '619764b79113'
down_revision: Union[str, None] = '69fda1fb161b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('form_structure', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_form_templates_id'), 'admission_form_templates', ['id'], unique=False)
    op.add_column('admission_applications', sa.Column('admission_form_template_id', sa.Integer(), nullable=False))
    op.add_column('admission_applications', sa.Column('form_data', sa.JSON(), nullable=False))
    op.drop_constraint('admission_applications_application_number_key', 'admission_applications', type_='unique')
    op.drop_constraint('admission_applications_class_applying_for_fkey', 'admission_applications', type_='foreignkey')
    op.drop_constraint('admission_applications_prospective_applicant_id_fkey', 'admission_applications', type_='foreignkey')
    op.drop_constraint('admission_applications_academic_session_id_fkey', 'admission_applications', type_='foreignkey')
    op.create_foreign_key(None, 'admission_applications', 'admission_form_templates', ['admission_form_template_id'], ['id'])
    op.drop_column('admission_applications', 'email')
    op.drop_column('admission_applications', 'relationship_to_student')
    op.drop_column('admission_applications', 'additional_info')
    op.drop_column('admission_applications', 'parent_address')
    op.drop_column('admission_applications', 'gender')
    op.drop_column('admission_applications', 'previous_school')
    op.drop_column('admission_applications', 'parent_occupation')
    op.drop_column('admission_applications', 'application_number')
    op.drop_column('admission_applications', 'date_of_birth')
    op.drop_column('admission_applications', 'prospective_applicant_id')
    op.drop_column('admission_applications', 'medical_conditions')
    op.drop_column('admission_applications', 'parent_first_name')
    op.drop_column('admission_applications', 'parent_phone')
    op.drop_column('admission_applications', 'parent_email')
    op.drop_column('admission_applications', 'class_applying_for')
    op.drop_column('admission_applications', 'first_name')
    op.drop_column('admission_applications', 'address')
    op.drop_column('admission_applications', 'last_name')
    op.drop_column('admission_applications', 'phone')
    op.drop_column('admission_applications', 'academic_session_id')
    op.drop_column('admission_applications', 'special_needs')
    op.drop_column('admission_applications', 'parent_last_name')
    op.drop_column('admission_applications', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_applications', sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('parent_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('special_needs', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('academic_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('class_applying_for', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('parent_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('parent_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('parent_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('medical_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('prospective_applicant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('application_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('parent_occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('previous_school', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('parent_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('admission_applications', sa.Column('relationship_to_student', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('admission_applications', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admission_applications', type_='foreignkey')
    op.create_foreign_key('admission_applications_academic_session_id_fkey', 'admission_applications', 'academic_sessions', ['academic_session_id'], ['id'])
    op.create_foreign_key('admission_applications_prospective_applicant_id_fkey', 'admission_applications', 'prospective_applicants', ['prospective_applicant_id'], ['id'])
    op.create_foreign_key('admission_applications_class_applying_for_fkey', 'admission_applications', 'classes', ['class_applying_for'], ['id'])
    op.create_unique_constraint('admission_applications_application_number_key', 'admission_applications', ['application_number'])
    op.drop_column('admission_applications', 'form_data')
    op.drop_column('admission_applications', 'admission_form_template_id')
    op.drop_index(op.f('ix_admission_form_templates_id'), table_name='admission_form_templates')
    op.drop_table('admission_form_templates')
    # ### end Alembic commands ###
