""""AddJoinCodeGeneratedAt"

Revision ID: 69fda1fb161b
Revises: 07d54dd5add9
Create Date: 2025-06-27 18:29:41.435169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fda1fb161b'
down_revision: Union[str, None] = '07d54dd5add9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('join_code_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'join_code_generated_at')
    # ### end Alembic commands ###
