""""Add_is_default_to_admission_form_template"

Revision ID: 6ee85bdba4bc
Revises: dc504e3c22b2
Create Date: 2025-06-28 11:40:45.078816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee85bdba4bc'
down_revision: Union[str, None] = 'dc504e3c22b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_form_templates', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.alter_column('admission_form_templates', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admission_form_templates', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('admission_form_templates', 'is_default')
    # ### end Alembic commands ###
