""""ConsolidateModelChanges"

Revision ID: 8d82cb696e3b
Revises: 54a8d59310ee
Create Date: 2025-06-27 16:17:37.405538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d82cb696e3b'
down_revision: Union[str, None] = '54a8d59310ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE subscriptionstatusenum AS ENUM ('TRIALING', 'ACTIVE', 'INACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE')")
    op.create_table('grading_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uses_gpa', sa.Boolean(), nullable=False),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('allows_astar_grade', sa.Boolean(), nullable=False),
    sa.Column('remarks_are_mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_grading_profiles_id'), 'grading_profiles', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('max_teachers', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('paystack_plan_code', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('paystack_plan_code')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('prospective_applicants',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_prospective_applicants_email'), 'prospective_applicants', ['email'], unique=True)
    op.create_index(op.f('ix_prospective_applicants_id'), 'prospective_applicants', ['id'], unique=False)
    op.add_column('admission_applications', sa.Column('prospective_applicant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admission_applications', 'prospective_applicants', ['prospective_applicant_id'], ['id'])
    op.drop_index('ix_roles_school_id', table_name='roles')
    op.create_foreign_key(None, 'roles', 'schools', ['school_id'], ['id'])
    op.add_column('school_subscriptions', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.add_column('school_subscriptions', sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'INACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE', name='subscriptionstatusenum'), nullable=True))
    op.add_column('school_subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('school_subscriptions', sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True))
    op.add_column('school_subscriptions', sa.Column('paystack_customer_code', sa.String(length=100), nullable=True))
    op.add_column('school_subscriptions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'school_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_column('school_subscriptions', 'is_active')
    op.drop_column('school_subscriptions', 'features')
    op.drop_column('school_subscriptions', 'plan_name')
    op.drop_column('school_subscriptions', 'max_teachers')
    op.drop_column('school_subscriptions', 'max_students')
    op.add_column('schools', sa.Column('grading_profile_id', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('schools', 'school_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('schools_subdomain_key', 'schools', type_='unique')
    op.create_foreign_key(None, 'schools', 'grading_profiles', ['grading_profile_id'], ['id'])
    op.drop_column('schools', 'is_boarding_school')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE subscriptionstatusenum")
    op.add_column('schools', sa.Column('is_boarding_school', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_unique_constraint('schools_subdomain_key', 'schools', ['subdomain'])
    op.alter_column('schools', 'school_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('schools', 'deleted_at')
    op.drop_column('schools', 'grading_profile_id')
    op.add_column('school_subscriptions', sa.Column('max_students', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('school_subscriptions', sa.Column('max_teachers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('school_subscriptions', sa.Column('plan_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('school_subscriptions', sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('school_subscriptions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'school_subscriptions', type_='foreignkey')
    op.drop_column('school_subscriptions', 'payment_method')
    op.drop_column('school_subscriptions', 'paystack_customer_code')
    op.drop_column('school_subscriptions', 'paystack_subscription_code')
    op.drop_column('school_subscriptions', 'auto_renew')
    op.drop_column('school_subscriptions', 'status')
    op.drop_column('school_subscriptions', 'plan_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_index('ix_roles_school_id', 'roles', ['school_id'], unique=False)
    op.drop_constraint(None, 'admission_applications', type_='foreignkey')
    op.drop_column('admission_applications', 'prospective_applicant_id')
    op.drop_index(op.f('ix_prospective_applicants_id'), table_name='prospective_applicants')
    op.drop_index(op.f('ix_prospective_applicants_email'), table_name='prospective_applicants')
    op.drop_table('prospective_applicants')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_grading_profiles_id'), table_name='grading_profiles')
    op.drop_table('grading_profiles')
    # ### end Alembic commands ###
