""""Seed_default_admission_form_templates"

Revision ID: bbd521313431
Revises: 6ee85bdba4bc
Create Date: 2025-06-28 11:47:08.490731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd521313431'
down_revision: Union[str, None] = '6ee85bdba4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    import json
    from datetime import datetime

    op.bulk_insert(
        sa.Table(
            'admission_form_templates',
            sa.MetaData(),
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('school_id', sa.Integer, nullable=True),
            sa.Column('name', sa.String, nullable=False),
            sa.Column('description', sa.String),
            sa.Column('is_active', sa.Boolean, default=True),
            sa.Column('form_structure', postgresql.JSONB, nullable=False),
            sa.Column('is_default', sa.Boolean, default=False),
            sa.Column('created_at', sa.DateTime(timezone=True)),
            sa.Column('updated_at', sa.DateTime(timezone=True)),
        ),
        [
            {
                'id': 1,
                'school_id': None,
                'name': 'Basic Application Form',
                'description': 'A simple application form for general admissions.',
                'is_active': True,
                'form_structure': json.dumps([
                    {"field_name": "applicant_full_name", "label": "Full Name of Applicant", "type": "text", "required": True, "placeholder": "Enter full name"},
                    {"field_name": "applicant_dob", "label": "Date of Birth", "type": "date", "required": True},
                    {"field_name": "applicant_email", "label": "Applicant Email", "type": "email", "required": True},
                    {"field_name": "applicant_phone", "label": "Applicant Phone Number", "type": "text", "required": False},
                    {"field_name": "applicant_address", "label": "Current Address", "type": "textarea", "required": True}
                ]),
                'is_default': True,
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow()
            },
            {
                'id': 2,
                'school_id': None,
                'name': 'K-12 Application Form',
                'description': 'Standard application form for K-12 admissions.',
                'is_active': True,
                'form_structure': json.dumps([
                    {"field_name": "applicant_full_name", "label": "Full Name of Applicant", "type": "text", "required": True, "placeholder": "Enter full name"},
                    {"field_name": "applicant_dob", "label": "Date of Birth", "type": "date", "required": True},
                    {"field_name": "parent_full_name", "label": "Parent/Guardian Full Name", "type": "text", "required": True},
                    {"field_name": "parent_email", "label": "Parent/Guardian Email", "type": "email", "required": True},
                    {"field_name": "previous_school_name", "label": "Previous School Attended", "type": "text", "required": False},
                    {"field_name": "grade_applying_for", "label": "Grade Applying For", "type": "select", "required": True, "options": ["Kindergarten", "1st Grade", "2nd Grade", "3rd Grade", "4th Grade", "5th Grade", "6th Grade", "7th Grade", "8th Grade", "9th Grade", "10th Grade", "11th Grade", "12th Grade"]},
                    {"field_name": "essay_question", "label": "Why do you want to join our school?", "type": "textarea", "required": False, "min_length": 50}
                ]),
                'is_default': True,
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow()
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM admission_form_templates WHERE id IN (1, 2)")
    # ### end Alembic commands ###
