""""Add_prospective_applicant_id_to_admission_applications"

Revision ID: dc504e3c22b2
Revises: 619764b79113
Create Date: 2025-06-28 11:30:33.063556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc504e3c22b2'
down_revision: Union[str, None] = '619764b79113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_applications', sa.Column('prospective_applicant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admission_applications', 'prospective_applicants', ['prospective_applicant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admission_applications', type_='foreignkey')
    op.drop_column('admission_applications', 'prospective_applicant_id')
    # ### end Alembic commands ###
