from .school import *
from .user import *
from .student import *
from .teacher import *
from .academic import *
from .attendance import *
from .assessment import *
from .fee import *
from .communication import *
from .timetable import *
from .admission import *
